version: '3'

services:
  planx_web:
    container_name: planX
    restart: always
    build: .

    command: bash -c "python3 manage.py migrate && gunicorn planX_project.wsgi:application --bind 0.0.0.0:8000"

    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}

    env_file: .env

    ports:
      - 8000:8000
