# Generated by Django 5.0.6 on 2024-05-10 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='links.link', verbose_name='Ссылка')),
            ],
        ),
    ]
