# Generated by Django 5.0.6 on 2024-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('links', '0002_alter_link_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='link',
        ),
        migrations.AddField(
            model_name='collection',
            name='links',
            field=models.ManyToManyField(related_name='collections', to='links.link', verbose_name='Ссылки'),
        ),
    ]
