# Generated by Django 5.0.6 on 2024-05-09 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок страницы')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка на страницу')),
                ('image', models.ImageField(default='', null=True, upload_to='', verbose_name='Изображение')),
                ('link_type', models.CharField(choices=[('website', 'вебсайт'), ('book', 'книга'), ('article', 'артикль'), ('music', 'музыка'), ('video', 'видео')], db_index=True, default='website', max_length=100, verbose_name='Тип ссылки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('link', 'user')},
            },
        ),
    ]
